name: sync

on:
  schedule:
    - cron:  '*/1 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run it
      run: go run main.go
